name: Naru
favicon: null
layout_spectrum: 0.7614848259836435
typography_spectrum: 0.499481329228729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8555547164287418
  lightness: 0.6145553786773235
  saturation: 0.5309418679680675
  rhythmicContrast: 0.8291454694699496
purpose: []
